export const PRODUCTS_FETCHED = "PRODUCTS_FETCHED";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const ATTRIBUTES_LOADING = "ATTRIBUTES_LOADING";
export const ATTRIBUTES_FETCHED = "ATTRIBUTES_FETCHED";
